### ISSUE TITLE
Generate a version metadata file which can be used by dotnet-install

### ISSUE THREAD

**Issue by mmitche** [dotnet/windowsdesktop#776] opened 2020-05-19 22:37 UTC
When the runtime or other components generates a stabilized build, it publishes to a non-stable directory, with an identical set of stable and suffixed asset names inside. This is so that dotnet-install, which makes an assumption that the version to install will match the asset name, will work properly. Example:

3.0.100-preview3-123545\sdk-3.0.100-preview3-123545.zip (contents are 3.0.100 branded) 
3.0.100-preview3-123545\sdk-3.0.100.zip (contents are 3.0.100 branded) 
We publish both so that we can push the final branded artifacts on release day, and the suffixed assets will work with dotnet-install. dotnet-install, however, will install the sdk, then look for the installed version (3.0.100-12345) rather than 3.0.100 because it knows nothing about the contents of the zip. It will fail.

We want to solve two problems

dotnet-install doesn't know what version to check for when it expands an archive
We have to double publish everything so that we still have the desired suffix-less assets for release day.
To solve this, the runtime, sdk, and aspnetcore repos should produce a file called productVersion.version, which inside, identifies the actual product version. Example:

productVersion.version -> contains 3.0.100
Thus, the dotnet-install script can find the blob directory of the files based on the passed in version, then look up the file containing the version number and use this to identify what the names of the runtime/sdk archives it should download as well as what it should verify it installed after it completes,.

**Comment by bozturkMSFT** [comment] 2020-06-17 15:30
The name `productVersion.txt` was used in the installer. Let's use the same name everywhere unless there is a good reason, please.

**Comment by dagood** [comment] 2020-07-17 21:12
Here's the dotnet/runtime instance of this issue: https://github.com/dotnet/runtime/issues/3833.

The sharedfx SDK seems like the right place to produce these fairly simple artifacts. /cc @NikolaMilosavljevic @jkoritzinsky

**Comment by bozturkMSFT** [comment] 2021-03-23 11:35
Any progress on this? Windowsdesktop seems to be the only runtime that doesn't generate this file.

**Comment by NikolaMilosavljevic** [comment] 2021-03-23 17:53
cc @merriemcgaw - it seems that the fix implemented in dotnet/runtime could be ported to windowsdesktop: https://github.com/dotnet/runtime/pull/41719

**Comment by merriemcgaw** [comment] 2021-03-23 19:00
@ryalanms - could you take a look at this for the WindowsDesktop repo?

**Comment by ryalanms** [comment] 2021-03-23 19:11
@merriemcgaw: Yes, I'll take a look.

@NikolaMilosavljevic:  What is the deadline to get this in?  Thanks.

**Comment by NikolaMilosavljevic** [comment] 2021-03-23 19:28
> @merriemcgaw: Yes, I'll take a look.
> 
> @NikolaMilosavljevic: What is the deadline to get this in? Thanks.

I'm not aware of the deadline. @bozturkMSFT is this a scenario blocker?

**Comment by bozturkMSFT** [comment] 2021-03-26 12:44
@ryalanms @NikolaMilosavljevic Starting .NET 6.0, this file is needed by dotnet-install.ps1 to install windowsdesktop runtime. Currently, the script fails as it cannot verify the version of the downloaded package.

Since we can't complete the work on install script side (https://github.com/dotnet/install-scripts/pull/113), I suspect https://github.com/dotnet/arcade/issues/5757 is also indirectly blocked. @mmitche @adiaaida

**Comment by adiaaida** [comment] 2021-04-07 14:51
Quick note on this: so that the files do not overlap in our aka.ms links, runtime, aspnetcore and installer all additionally produce a productVersion.txt file with the product name in the name of the file, ie runtime-productVersion.txt, aspnetcore-productVersion.txt, etc. WindowsDesktop will need to do this too.

**Comment by bekir-ozturk** [comment] 2021-05-21 08:45
The two issues I mentioned above (dotnet/install-scripts#113 & dotnet/arcade#5757) are now closed.
Any updates on this one?

**Comment by bekir-ozturk** [comment] 2021-09-16 11:16
@ryalanms @merriemcgaw This continues to become an [issue](https://github.com/dotnet/install-scripts/issues/214) and we are getting close to .NET 6 GA. When can we expect this work to be done?

**Comment by merriemcgaw** [comment] 2021-09-16 23:29
We are getting very close. @ryalanms ; @fabiant3 is this still on your radar? @vishalmsft might also want to know about it. There's not a lot of runway left for .NET 6; we're going to be locking down very very soon.

**Comment by RussKie** [comment] 2021-09-17 00:38
Is this what needs to happen https://github.com/dotnet/runtime/pull/41719?

**Comment by ryalanms** [comment] 2021-09-17 00:40
I have a build going containing the update in the internal queue.  I'll open a PR if it succeeds.

**Comment by ryalanms** [comment] 2021-09-17 04:58
There is now a productVersion.txt file created in the blob artifacts containing the version.  Is that the only update required?

https://dev.azure.com/dnceng/internal/_build/results?buildId=1367719&view=artifacts&pathAsName=false&type=publishedArtifacts

> Quick note on this: so that the files do not overlap in our aka.ms links, runtime, aspnetcore and installer all additionally produce a productVersion.txt file with the product name in the name of the file, ie runtime-productVersion.txt, aspnetcore-productVersion.txt, etc. WindowsDesktop will need to do this too.

This should be changed to WindowsDesktop-productVersion.txt?

**Comment by bekir-ozturk** [comment] 2021-09-20 05:16
> Is this what needs to happen [dotnet/runtime#41719](https://github.com/dotnet/runtime/pull/41719)?

Yes, except for one other thing. 
As @adiaaida mentioned [above](https://github.com/dotnet/windowsdesktop/issues/776#issuecomment-814979285), there also needs to a duplicate of the same file named "windowsdesktop-productVersion.txt".
@ryalanms Can you create the duplicate file as well?

**Comment by RussKie** [comment] 2021-09-20 05:21
I believe it has been done, please refer to #2131

https://github.com/dotnet/windowsdesktop/blob/9ad1fb8464899da4bdfdd98a59b84c2ef7cb009a/publish/prepare-artifacts.proj#L70-L82

**Comment by bekir-ozturk** [comment] 2021-09-20 05:30
Great! It wasn't available in the build @ryalanms shared above, but it seems to be fixed later.
I believe this issue can be closed now. Thank you all!

**Closed** 2021-09-20 22:54 UTC
